spring:
    application:
        name: ASM_Spring
    main:
        banner-mode: off
    thymeleaf:
        prefix: classpath:/templates/Admin/
    web:
        resources:
            static-locations: classpath:/static/Admin/


    datasource:
        url: jdbc:sqlserver://localhost;databaseName=asm_springboot;encrypt=true;trustServerCertificate=true
        username: sa
        password: 1211
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver

    jpa:
        hibernate:
            ddl-auto: update
            enable_lazy_load_no_trans: true
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.SQLServer2012Dialect

server:
    port: 8080
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 100MB
            max-request-size: 100MB
